server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liubenwei01
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #    开启confirms回调 p -> exchange
    #    开启returnedMessage回调 exchange -》 queue
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #手动确认
        prefetch: 100
    publisher-confirm-type: correlated