spring:
  datasource:

    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: liubenwei01
  mail:
    host: smtp.163.com
    username: liubenwwei00@163.com
    # |   password: liubenwei02
    protocol: smtp

    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: liubenwwei00@163.com
    password: DTOIWQOULTGURCYC
  rabbitmq:
    virtual-host: /
#    开启returndMessage回调到exchange
    publisher-returns: true
#    确认回调
    publisher-confirm-type: correlated
    listener:
      simple:
#        手动确认
        acknowledge-mode: manual
        prefetch: 100
mybatis:
  type-aliases-package: com.liu.manag.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml